# Алгоритмы обработки данных

## автор: Колеганов Николай


На входе датасет Бостон из ячейки [Трансформация таргета (целевой переменной]:


1.   Использовать различные преобразования данных для датасета Бостон,
с целью уменьшения средней абсолютной ошибки (MAE) на тестовой части при использовании линейной регрессии  (ячейки для запуска см. выше) 

2.   Составить таблицу, где зафиксировать преобразования и значение метрики

3.   Описать выводы, к которым Вы пришли.








Code of loading dataset:
------------------------------------------------------------------
dataset = load_boston()

target = np.array(dataset.feature_names) == "DIS"

X = dataset.data[:, np.logical_not(target)]

y = dataset.data[:, target].squeeze()

y_trans = QuantileTransformer(output_distribution='normal').fit_transform(dataset.data[:, target])







## Загрузка данных и библиотек

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression
from sklearn.metrics import median_absolute_error
from sklearn.compose import TransformedTargetRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.preprocessing import QuantileTransformer, quantile_transform
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.callbacks import ModelCheckpoint
from keras.optimizers import Adam, SGD, RMSprop
import tensorflow as tf
import matplotlib.pyplot as plt

Using TensorFlow backend.


# Подготавливаем и просматриваем данные

In [0]:
# отделяем фичи от таргета
dataset = load_boston()
target = np.array(dataset.feature_names) == "DIS"
x = dataset.data[:, np.logical_not(target)]
y = dataset.data[:, target].squeeze()

In [3]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [4]:
y

array([ 4.09  ,  4.9671,  4.9671,  6.0622,  6.0622,  6.0622,  5.5605,
        5.9505,  6.0821,  6.5921,  6.3467,  6.2267,  5.4509,  4.7075,
        4.4619,  4.4986,  4.4986,  4.2579,  3.7965,  3.7965,  3.7979,
        4.0123,  3.9769,  4.0952,  4.3996,  4.4546,  4.682 ,  4.4534,
        4.4547,  4.239 ,  4.233 ,  4.175 ,  3.99  ,  3.7872,  3.7598,
        3.3603,  3.3779,  3.9342,  3.8473,  5.4011,  5.4011,  5.7209,
        5.7209,  5.7209,  5.7209,  5.1004,  5.1004,  5.6894,  5.87  ,
        6.0877,  6.8147,  6.8147,  6.8147,  6.8147,  7.3197,  8.6966,
        9.1876,  8.3248,  7.8148,  6.932 ,  7.2254,  6.8185,  7.2255,
        7.9809,  9.2229,  6.6115,  6.6115,  6.498 ,  6.498 ,  6.498 ,
        5.2873,  5.2873,  5.2873,  5.2873,  4.2515,  4.5026,  4.0522,
        4.0905,  5.0141,  4.5026,  5.4007,  5.4007,  5.4007,  5.4007,
        4.7794,  4.4377,  4.4272,  3.7476,  3.4217,  3.4145,  3.0923,
        3.0921,  3.6659,  3.6659,  3.615 ,  3.4952,  3.4952,  3.4952,
        3.4952,  3.4

## Cоздаем пустой pandas dataframe для выводов

In [0]:
columns =['Trasnform type', 'MAE']
conclusions = pd.DataFrame(columns=columns)

## Делим данные для train и test

In [0]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1)

# Обучаем регрессию на исходных данных

In [7]:
regr = LinearRegression()
regr.fit(x_train, y_train)
y_pred = regr.predict(x_test)
print(y_pred)

[5.38993768 6.07672321 4.08312286 5.89384695 1.68846199 2.10466753
 8.05993425 3.41488745 2.7640194  4.19915205 2.88124927 6.56939446
 3.6858715  7.96381297 3.24779259 1.98257576 1.93531676 3.0753205
 7.62714302 1.08846052 3.56300405 0.76920512 3.15907388 4.59907
 8.04121338 2.17960513 3.63695434 4.86580372 2.95521667 2.03052308
 7.15145511 5.41355445 7.79306216 1.61120326 4.90531324 4.08615336
 1.72052261 4.57537207 2.26653226 2.78142895 5.13552364 4.79363464
 3.57368831 2.58241238 2.24601131 2.21502256 1.18620069 1.87583754
 1.92885317 3.7652489  2.67728895 5.62653675 4.63292546 1.82790457
 2.11423674 5.24094625 2.52135716 3.8792763  3.82790437 3.40515035
 1.60338792 4.53873607 1.98761973 2.7313058  5.53511197 4.30395812
 3.29839029 3.95074425 4.27043684 1.97326663 4.84470764 1.95685887
 2.20146927 3.53375507 3.73500454 3.87092266 1.6929484  6.98597187
 0.37181941 7.84976376 2.13963736 3.2275562  5.96822862 1.78168219
 6.42811875 7.59649375 1.80122141 5.09080843 3.56290304 2.19169082

In [8]:
# считаем MAE на исходных данных
MAE_pure = np.round(median_absolute_error(y_test, y_pred), 2)
print(MAE_pure)

0.63


In [0]:
# добавляем строку в таблицу с выводами
mae_pure_row = pd.DataFrame([['No transformation', MAE_pure]], columns=('Trasnform type', 'MAE'))
conclusions = conclusions.append(mae_pure_row)

**Стандартизация (Z-преобразование)**

In [0]:
dataset = load_boston()
target = np.array(dataset.feature_names) == "DIS"
x_z = dataset.data[:, np.logical_not(target)]
y_z = dataset.data[:, target].squeeze()

In [0]:
scaler = preprocessing.StandardScaler().fit(x_z)

In [12]:
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [0]:
X_stand = scaler.transform(x_z)

In [14]:
X_stand

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [15]:
X_stand.mean(axis=0)

array([-1.12338772e-16,  7.89881994e-17,  2.10635198e-16, -3.51058664e-17,
       -1.96592852e-16, -1.08828186e-16, -1.47444639e-16, -1.12338772e-16,
        0.00000000e+00, -4.21270397e-16, -7.44244367e-16, -3.08931624e-16])

In [16]:
X_stand.var(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
# делим преобразованный датасет на тренировочный и тестовый
X_train_st, X_test_st, y_train_st, y_test_st = train_test_split(X_stand, y_z, random_state=1)

## Обучаем на получившихся

In [0]:
# обучаем на стандартизованных данных 
regr_ST = LinearRegression()
regr_ST.fit(X_train_st, y_train_st)
y_pred_ST = regr_ST.predict(X_test_st)

In [19]:
# Считаем MAE на преобразованных данных 
MAE_ST = np.round(median_absolute_error(y_test_st, y_pred_ST), 2) 
print(MAE_ST)

0.63


In [0]:
# добавляем строку в таблицу с выводами
mae_st_row = pd.DataFrame([['StandardScaler', MAE_ST]], columns=('Trasnform type', 'MAE'))
conclusions =  conclusions.append(mae_st_row, ignore_index=True)

**Шкалирование к диапазону**

In [0]:
min_max_scaler = preprocessing.MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(x)

In [22]:
X_minmax

array([[0.00000000e+00, 1.80000000e-01, 6.78152493e-02, ...,
        2.87234043e-01, 1.00000000e+00, 8.96799117e-02],
       [2.35922539e-04, 0.00000000e+00, 2.42302053e-01, ...,
        5.53191489e-01, 1.00000000e+00, 2.04470199e-01],
       [2.35697744e-04, 0.00000000e+00, 2.42302053e-01, ...,
        5.53191489e-01, 9.89737254e-01, 6.34657837e-02],
       ...,
       [6.11892474e-04, 0.00000000e+00, 4.20454545e-01, ...,
        8.93617021e-01, 1.00000000e+00, 1.07891832e-01],
       [1.16072990e-03, 0.00000000e+00, 4.20454545e-01, ...,
        8.93617021e-01, 9.91300620e-01, 1.31070640e-01],
       [4.61841693e-04, 0.00000000e+00, 4.20454545e-01, ...,
        8.93617021e-01, 1.00000000e+00, 1.69701987e-01]])

In [23]:
X_minmax.var(axis=0)

array([0.00932841, 0.05428618, 0.06311681, 0.06438548, 0.0567372 ,
       0.01808855, 0.08387336, 0.14303692, 0.10324509, 0.05293941,
       0.0528898 , 0.03875164])

In [0]:
# делим преобразованный датасет на тренировочный и тестовый
X_train_MM, X_test_MM, y_train_MM, y_test_MM = train_test_split(X_minmax, y, random_state=1)

## Обучаем 

In [0]:
regr_MM = LinearRegression()
regr_MM.fit(X_train_MM, y_train_MM)
y_pred_MM = regr_MM.predict(X_test_MM)

In [26]:
# Считаем MAE на преобразованных данных 
MAE_MM = np.round(median_absolute_error(y_test_MM, y_pred_MM), 2) 
print(MAE_MM)

0.63


In [0]:
# добавляем строку в таблицу с выводами
mae_mm_row = pd.DataFrame([['MinMaxScaler', MAE_MM]], columns=('Trasnform type', 'MAE'))
conclusions =  conclusions.append(mae_mm_row, ignore_index=True)

**Обработка выбросов**

In [28]:
transformer = preprocessing.RobustScaler().fit(x)
transformer

RobustScaler(copy=True, quantile_range=(25.0, 75.0), with_centering=True,
             with_scaling=True)

In [0]:
X_stand_r = transformer.transform(x)

In [30]:
X_stand_r

array([[-0.06959315,  1.44      , -0.57164988, ..., -1.33928571,
         0.26190191, -0.63768116],
       [-0.06375455,  0.        , -0.20294345, ..., -0.44642857,
         0.26190191, -0.22188906],
       [-0.06376011,  0.        , -0.20294345, ..., -0.44642857,
         0.06667466, -0.73263368],
       ...,
       [-0.05445006,  0.        ,  0.17350891, ...,  0.69642857,
         0.26190191, -0.57171414],
       [-0.04086745,  0.        ,  0.17350891, ...,  0.69642857,
         0.09641444, -0.48775612],
       [-0.05816351,  0.        ,  0.17350891, ...,  0.69642857,
         0.26190191, -0.34782609]])

In [0]:
# делим преобразованный датасет на тренировочный и тестовый
X_train_RS, X_test_RS, y_train_RS, y_test_RS = train_test_split(X_stand_r, y, random_state=1)

## Обучаем

In [0]:
# обучаем на преобразованных данных 
regr_RS = LinearRegression()
regr_RS.fit(X_train_RS, y_train_RS)
y_pred_RS = regr_RS.predict(X_test_RS)

In [33]:
# Считаем MAE на преобразованных данных 
MAE_RS = np.round(median_absolute_error(y_test_RS, y_pred_RS), 2) 
print(MAE_RS)

0.63


In [0]:
# добавляем строку в таблицу с выводами
mae_mm_rs = pd.DataFrame([['RobustScaler', MAE_RS]], columns=('Trasnform type', 'MAE'))
conclusions =  conclusions.append(mae_mm_rs, ignore_index=True)

# Приведение к распределению Гаусса

In [0]:
# используем преобразование Йео-Джонсона по умолчанию
power_tran = preprocessing.PowerTransformer(standardize=True)
X_PT = power_tran.fit_transform(x)

In [0]:
# делим преобразованный датасет на тренировочный и тестовый
X_train_PT, X_test_PT, y_train_PT, y_test_PT = train_test_split(X_PT, y, random_state=1)

## Обучаем

In [0]:
regr_PT = LinearRegression()
regr_PT.fit(X_train_PT, y_train_PT)
y_pred_PT = regr_PT.predict(X_test_PT)

In [38]:
# Считаем MAE на преобразованных данных 
MAE_PT = np.round(median_absolute_error(y_test_PT, y_pred_PT), 2) 
print(MAE_PT)

0.7


In [0]:
# добавляем строку в таблицу с выводами
mae_mm_pt = pd.DataFrame([['PowerTransformer', MAE_PT]], columns=('Trasnform type', 'MAE'))
conclusions =  conclusions.append(mae_mm_pt, ignore_index=True)

**Преобразование при помощи квантилей**

---



In [40]:
quantile_tran = preprocessing.QuantileTransformer(output_distribution='normal', random_state=0)
X_trans = quantile_tran.fit_transform(x)


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_data.py:2357: UserWarning: n_quantiles (1000) is greater than the total number of samples (506). n_quantiles is set to n_samples.
  % (self.n_quantiles, n_samples))


In [41]:
X_trans

array([[-5.19933758,  0.70121585, -1.48097265, ..., -1.06007845,
         5.19933758, -1.17103637],
       [-1.66934259, -5.19933758, -0.26104292, ..., -0.4682526 ,
         5.19933758, -0.33106676],
       [-1.68968043, -5.19933758, -0.26104292, ..., -0.4682526 ,
         0.14193834, -1.51137447],
       ...,
       [-0.89221589, -5.19933758,  0.21762312, ...,  1.53512765,
         5.19933758, -0.98473862],
       [-0.45996053, -5.19933758,  0.21762312, ...,  1.53512765,
         0.24055376, -0.79991098],
       [-1.08656811, -5.19933758,  0.21762312, ...,  1.53512765,
         5.19933758, -0.49332612]])

In [0]:
# делим преобразованный датасет на тренировочный и тестовый
X_train_QT, X_test_QT, y_train_QT, y_test_QT = train_test_split(X_trans, y, random_state=1)

## Обучаем

In [0]:
regr_QT = LinearRegression()
regr_QT.fit(X_train_QT, y_train_QT)
y_pred_QT = regr_QT.predict(X_test_QT)

In [44]:
# Считаем MAE на преобразованных данных 
MAE_QT = np.round(median_absolute_error(y_test_QT, y_pred_QT), 2) 
print(MAE_QT)

0.78


In [0]:
# добавляем строку в таблицу с выводами
mae_mm_qt = pd.DataFrame([['QuantileTransformer', MAE_QT]], columns=('Trasnform type', 'MAE'))
conclusions =  conclusions.append(mae_mm_qt, ignore_index=True)

# Дискретизация непрерывных переменных

## Датасета для дискретезации непрерывных переменных

In [46]:
disc_dataset = pd.DataFrame(dataset.data, columns = dataset.feature_names)
disc_dataset.head(3)

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03

[3 rows x 13 columns]

In [47]:
# удаляем колонку с таргетом
disc_dataset = disc_dataset.drop(columns='DIS')
disc_dataset.head(3)

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03

[3 rows x 12 columns]

## Дискретизация колонки

In [48]:
D = preprocessing.KBinsDiscretizer(n_bins=[400], encode='ordinal')
disc_dataset['PTRATIO'] = D.fit_transform(disc_dataset['PTRATIO'].values.reshape(disc_dataset.shape[0],-1))

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_discretization.py:197: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.
  'decreasing the number of bins.' % jj)


In [0]:
# делим преобразованный pandas датасет на тренировочный и тестовый
X_train_D, X_test_D, y_train_D, y_test_D = train_test_split(disc_dataset, y, random_state=1)

## Обучаем

In [0]:
regr_D = LinearRegression()
regr_D.fit(X_train_D, y_train_D)
y_pred_D = regr_D.predict(X_test_D)

In [51]:
# Считаем MAE на преобразованных данных 
MAE_D = np.round(median_absolute_error(y_test_D, y_pred_D), 2) 
print(MAE_D)

0.62


In [0]:
# добавляем строку в таблицу с выводами
mae_mm_bd = pd.DataFrame([['KBinsDiscretizer', MAE_D]], columns=('Trasnform type', 'MAE'))
conclusions =  conclusions.append(mae_mm_bd, ignore_index=True)

**Бинаризация непрерывной переменной**

In [53]:
bin_dataset = pd.DataFrame(dataset.data, columns = dataset.feature_names)
bin_dataset.head(3)

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03

[3 rows x 13 columns]

удаляю target

In [54]:
bin_dataset = bin_dataset.drop(columns='DIS')
bin_dataset.head(3)

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03

[3 rows x 12 columns]

In [0]:
BD = preprocessing.Binarizer(threshold=0.9)
bin_dataset['LSTAT'] = BD.fit_transform(bin_dataset['LSTAT'].values.reshape(bin_dataset.shape[0],-1))

In [0]:
# делим преобразованный pandas датасет на тренировочный и тестовый
X_train_BIN, X_test_BIN, y_train_BIN, y_test_BIN = train_test_split(bin_dataset, y, random_state=1)

## Обучаем

In [0]:
regr_BIN = LinearRegression()
regr_BIN.fit(X_train_BIN, y_train_BIN)
y_pred_BIN = regr_BIN.predict(X_test_BIN)

In [58]:
MAE_BIN = np.round(median_absolute_error(y_test_BIN, y_pred_BIN), 2) 
print(MAE_BIN)

0.64


In [0]:
# добавляем строку в таблицу с выводами
mae_mm_bin = pd.DataFrame([['Binarizer', MAE_BIN]], columns=('Trasnform type', 'MAE'))
conclusions =  conclusions.append(mae_mm_bin, ignore_index=True)

# Трансформация таргета (целевой переменной)

In [0]:
dataset = load_boston()
target = np.array(dataset.feature_names) == "DIS"
x_t = dataset.data[:, np.logical_not(target)]
y_t = dataset.data[:, target].squeeze()

In [0]:
# делим датасет на тренировочный и тестовый для трансформации таргета
X_train_TS, X_test_TS, y_train_TS, y_test_TS = train_test_split(x_t, y_t, random_state=1)

## Обучаем

In [62]:
regr_TS = TransformedTargetRegressor(
    regressor=LinearRegression(),
    transformer=QuantileTransformer(output_distribution='normal'))
regr_TS.fit(X_train_TS, y_train_TS)
y_pred_TS = regr_TS.predict(X_test_TS)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_data.py:2357: UserWarning: n_quantiles (1000) is greater than the total number of samples (379). n_quantiles is set to n_samples.
  % (self.n_quantiles, n_samples))


In [63]:
MAE_TS = np.round(median_absolute_error(y_test_TS, y_pred_TS), 2)
print(MAE_TS)

0.53


In [0]:
# добавляем строку в таблицу с выводами
mae_mm_ts = pd.DataFrame([['TransformedTarget', MAE_TS]], columns=('Trasnform type', 'MAE'))
conclusions =  conclusions.append(mae_mm_ts, ignore_index=True)

# Увеличение размерности пространства

In [0]:
dataset = load_boston()
target = np.array(dataset.feature_names) == "DIS"
x_p = dataset.data[:, np.logical_not(target)]
y_p = dataset.data[:, target].squeeze()

In [0]:
poly = PolynomialFeatures(2,interaction_only=True)
X_poly = poly.fit_transform(x_p)                             

In [0]:
X_train_pol, X_test_pol, y_train_pol, y_test_pol = train_test_split(X_poly, y_p, random_state=1)

## Обучаем

In [0]:
regr_INC = LinearRegression()
regr_INC.fit(X_train_pol, y_train_pol)
y_pred_INC = regr_INC.predict(X_test_pol)

In [69]:
MAE_INC = np.round(median_absolute_error(y_test_pol, y_pred_INC), 2)
print(MAE_INC)

0.55


In [0]:
# добавляем строку в таблицу с выводами
mae_mm_inc = pd.DataFrame([['PolynomialFeatures', MAE_INC]], columns=('Trasnform type', 'MAE'))
conclusions =  conclusions.append(mae_mm_inc, ignore_index=True)

# Снижение размерности пространства

In [0]:
PCA_trans = PCA(n_components=6)
X_PCA = PCA_trans.fit_transform(x)

In [0]:
# делим преобразованный pandas датасет на тренировочный и тестовый
X_train_PCA, X_test_PCA, y_train_PCA, y_test_PCA = train_test_split(X_PCA, y, random_state=1)

## Обучаем

In [0]:
regr_PCA = LinearRegression()
regr_PCA.fit(X_train_PCA, y_train_PCA)
y_pred_PCA = regr_PCA.predict(X_test_PCA)

In [74]:
MAE_PCA = np.round(median_absolute_error(y_test_PCA, y_pred_PCA), 2)
print(MAE_PCA)

0.59


In [0]:
# добавляем строку в таблицу с выводами
mae_mm_pca = pd.DataFrame([['PCA', MAE_PCA]], columns=('Trasnform type', 'MAE'))
conclusions =  conclusions.append(mae_mm_pca, ignore_index=True)

# T-Distributed Stochastic Neighbouring Entities (t-SNE)

In [0]:
tNSE_trans = TSNE(n_components=2, verbose=0, perplexity=80, n_iter=1000)
X_tNSE = tNSE_trans.fit_transform(x)

In [0]:
# делим преобразованный pandas датасет на тренировочный и тестовый
X_train_tNSE, X_test_tNSE, y_train_tNSE, y_test_tNSE = train_test_split(X_tNSE, y, random_state=1)

## Обучаем

In [0]:
regr_tNSE = LinearRegression()
regr_tNSE.fit(X_train_tNSE, y_train_tNSE)
y_pred_tNSE = regr_tNSE.predict(X_test_tNSE)

In [79]:
MAE_TNSE = np.round(median_absolute_error(y_test_tNSE, y_pred_tNSE), 2)
print(MAE_TNSE)

0.91


In [0]:
mae_mm_tnse = pd.DataFrame([['TNSE', MAE_TNSE]], columns=('Trasnform type', 'MAE'))
conclusions =  conclusions.append(mae_mm_tnse, ignore_index=True)

# Результат

In [81]:
conclusions

Trasnform type   MAE
0     No transformation  0.63
1        StandardScaler  0.63
2          MinMaxScaler  0.63
3          RobustScaler  0.63
4      PowerTransformer  0.70
5   QuantileTransformer  0.78
6      KBinsDiscretizer  0.62
7             Binarizer  0.64
8     TransformedTarget  0.53
9    PolynomialFeatures  0.55
10                  PCA  0.59
11                 TNSE  0.91